/*
Program name: EECS 348 Assignment 3
Brief description: C++ program that prioritizes a CEO's emails with a
list-based MaxHeap built from scratch
Inputs: a test file of EMAIL, NEXT, READ and COUNT commands, named on the
command line or piped in on standard input
Outputs: email counts and the next email to read, printed to the terminal
Author: Francis Tryban
Creation date: 10-01-2026
Revision date: 10-01-2026
Revisions: rewrote run 00 under AGENT.md rules (comments, prolog, input
cleanup, error messages, one method per command); then replaced std::endl
with '\n' in the two output methods, which removed a measured slowdown;
moved code attribution from every function to one line per section
Collaborators: none
Other sources: OpenAI Codex (GPT-6 Luna) generated this code from my
specification; Claude Opus 5.5 helped me write the rules in AGENT.md,
tested this code, and made the std::endl edit in handleCount and handleNext
*/
#include <cctype> // include character checks
#include <fstream> // include file input
#include <iostream> // include terminal and stream input
#include <string> // include text strings
#include <vector> // include a resizable list for the heap

// ---------------------------------------------------------------------------
// Email: one message plus the two numbers that decide its place in line
// generated by Codex (GPT-6 Luna), reviewed by me
// ---------------------------------------------------------------------------
class Email { // one email
public: // the heap and the program both read these
	std::string sender; // store the sender category
	std::string subject; // store the subject text
	std::string date; // store the displayed date
	int senderRank; // store the sender's priority rank
	int dateRank; // store the date as a sortable number
	unsigned long long arrivalOrder; // store the order the email arrived

	// create an email and calculate its priority values once
	Email(const std::string& senderValue, const std::string& subjectValue, // const & means borrow the caller's text without copying or changing it
	      const std::string& dateValue, unsigned long long orderValue) // the date and the email's place in the file
		: sender(senderValue), subject(subjectValue), date(dateValue), senderRank(0), dateRank(0), arrivalOrder(orderValue) { // set its fields and initial ranks
		if (sender == "Boss") senderRank = 5; // give the boss the highest sender rank
		else if (sender == "Subordinate") senderRank = 4; // rank subordinate emails next
		else if (sender == "Peer") senderRank = 3; // rank peer emails next
		else if (sender == "ImportantPerson") senderRank = 2; // rank important person emails next
		else senderRank = 1; // rank other person emails last
		// turn MM-DD-YYYY into the number YYYYMMDD, so a bigger number is a newer date
		// subtracting '0' turns a digit character like '7' into the number 7
		dateRank = (date[6] - '0') * 10000000 + (date[7] - '0') * 1000000 // first two year digits
		         + (date[8] - '0') * 100000 + (date[9] - '0') * 10000 // last two year digits
		         + (date[0] - '0') * 1000 + (date[1] - '0') * 100 // month
		         + (date[3] - '0') * 10 + (date[4] - '0'); // day
	} // end of Email

	// say whether this email should appear before another
	bool outranks(const Email& other) const { // compare the saved priority values
		if (senderRank != other.senderRank) return senderRank > other.senderRank; // prefer the higher sender rank
		if (dateRank != other.dateRank) return dateRank > other.dateRank; // prefer the newer date
		return arrivalOrder < other.arrivalOrder; // prefer the one entered first when tied
	} // end of outranks
}; // end of Email

// ---------------------------------------------------------------------------
// MaxHeap: the priority queue, built by hand on a vector
// generated by Codex (GPT-6 Luna), reviewed by me
// ---------------------------------------------------------------------------
class MaxHeap { // define a heap that keeps the highest priority email first
private: // only the heap itself touches the list
	std::vector<Email> items; // store the heap as a resizable list

	// exchange two emails in the list
	void swapItems(std::size_t first, std::size_t second) { // swap the selected positions
		Email temporary = items[first]; // hold the first email while swapping
		items[first] = items[second]; // move the second email into the first position
		items[second] = temporary; // place the saved email in the second position
	} // end of swapItems

	// move a new email up to its proper position
	void siftUp(std::size_t index) { // repair the heap from a new item toward the root
		while (index > 0) { // continue until the item reaches the root
			std::size_t parent = (index - 1) / 2; // find this item's parent position
			if (!items[index].outranks(items[parent])) break; // stop when the parent already ranks first
			swapItems(index, parent); // move the higher priority email upward
			index = parent; // continue from the parent's old position
		} // end of siftUp loop
	} // end of siftUp

	// move a root replacement down to its proper position
	void siftDown(std::size_t index) { // repair the heap from the root toward the leaves
		while (true) { // keep checking until the item is in place
			std::size_t left = index * 2 + 1; // find the left child position
			std::size_t right = index * 2 + 2; // find the right child position
			std::size_t best = index; // start with the current item as highest priority
			if (left < items.size() && items[left].outranks(items[best])) best = left; // select the left child if it ranks higher
			if (right < items.size() && items[right].outranks(items[best])) best = right; // select the right child if it ranks higher
			if (best == index) break; // stop when neither child ranks higher
			swapItems(index, best); // move the higher priority email upward
			index = best; // continue from the child's old position
		} // end of siftDown loop
	} // end of siftDown

public: // what the rest of the program is allowed to call
	bool empty() const { // check whether the list is empty
		return items.empty(); // return the list's empty status
	} // end of empty

	std::size_t size() const { // get the current number of emails
		return items.size(); // return the list length
	} // end of size

	// add an email and repair the heap
	void insert(const Email& email) { // add one email to the list
		items.push_back(email); // put it at the end of the list
		siftUp(items.size() - 1); // move it upward as needed
	} // end of insert

	// return the first email or nullptr when the heap is empty
	const Email* top() const { // look at the highest priority email
		if (items.empty()) return nullptr; // report no email when the heap is empty
		return &items[0]; // return a pointer to the root email
	} // end of top

	// remove the highest priority email if one exists
	void removeTop() { // drop the root and repair the heap
		if (items.empty()) return; // leave an empty heap unchanged
		if (items.size() == 1) { // handle the single email case
			items.pop_back(); // remove the only email
			return; // finish after removing the only email
		} // end of single email case
		items[0] = items.back(); // move the last email to the root
		items.pop_back(); // remove the old last position
		siftDown(0); // restore heap order from the root
	} // end of removeTop
}; // end of MaxHeap

// ---------------------------------------------------------------------------
// EmailProgram: reads the test file and runs each command on the inbox
// generated by Codex (GPT-6 Luna), reviewed by me; output lines in handleCount
// and handleNext edited by me with Claude Opus 5.5 (see Revisions)
// ---------------------------------------------------------------------------
class EmailProgram { // the command processor
private: // keep program state and command methods private
	MaxHeap inbox; // store unread emails in priority order
	unsigned long long nextOrder = 0; // track input order for exact priority ties

	// remove spaces, tabs and carriage returns from both ends
	std::string trim(const std::string& value) const { // return a cleaned copy of the text
		std::size_t first = 0; // begin at the first character
		while (first < value.size() && (value[first] == ' ' || value[first] == '\t' || value[first] == '\r')) ++first; // skip allowed leading whitespace
		std::size_t last = value.size(); // begin just beyond the last character
		while (last > first && (value[last - 1] == ' ' || value[last - 1] == '\t' || value[last - 1] == '\r')) --last; // skip allowed trailing whitespace
		return value.substr(first, last - first); // return the text between the ends
	} // end of trim

	// check that a date has the required digit pattern
	bool validDate(const std::string& dateValue) const { // confirm the date shape and digits
		if (dateValue.size() != 10) return false; // require ten characters
		if (dateValue[2] != '-' || dateValue[5] != '-') return false; // require dashes in the expected places
		for (std::size_t index = 0; index < dateValue.size(); ++index) { // check every character
			if (index == 2 || index == 5) continue; // skip the two required separators
			if (std::isdigit(static_cast<unsigned char>(dateValue[index])) == 0) return false; // reject a non-digit
		} // end of digit check loop
		return true; // accept the correctly shaped date
	} // end of validDate

	// handle an EMAIL command and report bad records
	void handleEmail(const std::string& line) { // parse fields and insert a valid email
		std::string fields = line.substr(5); // take the text after EMAIL
		std::size_t firstComma = fields.find(','); // locate the sender separator
		std::size_t secondComma = firstComma == std::string::npos ? std::string::npos : fields.find(',', firstComma + 1); // locate the subject separator
		if (firstComma == std::string::npos || secondComma == std::string::npos) { // catch missing fields
			std::cerr << "Skipped invalid EMAIL command: expected sender, subject and date.\n"; // explain the malformed row
			return; // continue with the next command
		} // end of missing fields check
		std::string senderValue = trim(fields.substr(0, firstComma)); // clean the sender field
		std::string subjectValue = trim(fields.substr(firstComma + 1, secondComma - firstComma - 1)); // clean the subject field
		std::string dateValue = trim(fields.substr(secondComma + 1)); // clean the date field
		bool knownSender = senderValue == "Boss" || senderValue == "Subordinate" || senderValue == "Peer" || senderValue == "ImportantPerson" || senderValue == "OtherPerson"; // check the allowed sender names
		if (!knownSender || subjectValue.empty() || !validDate(dateValue)) { // reject missing or invalid email data
			std::cerr << "Skipped invalid EMAIL command: sender, subject or date is invalid.\n"; // explain why this row was skipped
			return; // continue with the next command
		} // end of invalid data check
		inbox.insert(Email(senderValue, subjectValue, dateValue, nextOrder)); // add the validated email to the heap
		++nextOrder; // reserve the next input order for the next email
	} // end of handleEmail

	// handle a COUNT command
	void handleCount() const { // print the current unread email count
		std::cout << "There are " << inbox.size() << " emails to read." << '\n'; // display the count; '\n' ends the line without endl's slow flush
	} // end of handleCount

	// handle a NEXT command
	void handleNext() const { // display but keep the highest priority email
		const Email* email = inbox.top(); // get the root email or an empty result
		if (email == nullptr) { // handle an empty inbox
			std::cout << "No emails to read." << '\n'; // tell the CEO the inbox is empty
			return; // finish this command
		} // end of empty inbox check
		std::cout << "Next email:\n"; // announce the next email
		std::cout << "Sender: " << email->sender << '\n'; // display the sender category
		std::cout << "Subject: " << email->subject << '\n'; // display the subject text
		std::cout << "Date: " << email->date << '\n'; // display the date
	} // end of handleNext

	// handle a READ command
	void handleRead() { // remove the highest priority email
		inbox.removeTop(); // removeTop safely handles an empty inbox
	} // end of handleRead

	// clean a line and send it to the matching command method
	void handleLine(const std::string& rawLine) { // dispatch one input line
		std::string line = trim(rawLine); // clean whitespace at the ends
		if (line.compare(0, 6, "EMAIL ") == 0) { // identify an EMAIL command
			handleEmail(line); // parse and insert the email
		} else if (line == "COUNT") { // identify a COUNT command
			handleCount(); // print the unread count
		} else if (line == "NEXT") { // identify a NEXT command
			handleNext(); // display the next email
		} else if (line == "READ") { // identify a READ command
			handleRead(); // remove the next email
		} // end of command selection
	} // end of handleLine

public: // make the input loop available to main
	// read and process each command line
	void run(std::istream& input) { // process commands until input ends
		std::string line; // hold the current command line
		while (std::getline(input, line)) { // read one command at a time
			handleLine(line); // clean and process the command
		} // end of input loop
	} // end of run
}; // end of EmailProgram

// ---------------------------------------------------------------------------
// main: pick the input, then hand it to the program object
// generated by Codex (GPT-6 Luna), reviewed by me
// ---------------------------------------------------------------------------
int main(int argc, char* argv[]) { // start from a named file or standard input
	if (argc > 2) { // reject extra command-line arguments
		std::cerr << "Usage: " << argv[0] << " [input-file]\n"; // show the allowed command format
		return 1; // exit with an error status
	} // end of argument count check
	std::ifstream file; // prepare a file stream for optional input
	std::istream* input = &std::cin; // use standard input unless a file is named
	if (argc == 2) { // check whether a filename was supplied
		file.open(argv[1]); // open the requested input file
		if (!file) { // handle a file that could not be opened
			std::cerr << "Error: could not open input file.\n"; // explain the file error
			return 1; // exit with an error status
		} // end of file open check
		input = &file; // read commands from the opened file
	} // end of filename selection
	EmailProgram program; // create the object that processes commands
	program.run(*input); // process the selected input stream
	return 0; // report normal completion
} // end of main
